export const fields = [
  { value: '', label: 'SHOW ALL' },
  { value: 'buick', label: 'Buick' },
  { value: 'volvo', label: 'Volvo' },
  { value: 'hummer', label: 'Hummer' },
  { value: 'subaru', label: 'Subaru' },
  { value: 'mitsubishi', label: 'Mitsubishi' },
  { value: 'nissan', label: 'Nissan' },
  { value: 'gmc', label: 'GMC' },
  { value: 'hyundai', label: 'Hyundai' },
  { value: 'lincoln', label: 'Lincoln' },
  { value: 'bentley', label: 'Bentley' },
  { value: 'honda', label: 'Honda' },
  { value: 'ford', label: 'Ford' },
  { value: 'chevrolet', label: 'Chevrolet' },
  { value: 'bmw', label: 'BMW' },
  { value: 'mercedes-benz', label: 'Mercedes-Benz' },
  { value: 'audi', label: 'Audi' },
  { value: 'tesla', label: 'Tesla' },
  { value: 'mazda', label: 'Mazda' },
  { value: 'lexus', label: 'Lexus' },
  { value: 'volkswagen', label: 'Volkswagen' },
  { value: 'porsche', label: 'Porsche' },
];
